### ISSUE TITLE
handle empty `MINGW_PACKAGE_PREFIX` for `:p`

### ISSUE THREAD

**Issue by goyalyashpal** [renatosilva/pactoys#6]
_Originally posted by @me in https://github.com/msys2/MSYS2-packages/issues/3457#issuecomment-1368406689_

### Summary of problem
- When the variable `MINGW_PACKAGE_PREFIX` is not set, ...
- the `pacboy -S <name>:p` returns the `pacman` usage manual
- which renders the newcomers clueless

Reason being:
- this above command "translates" to `pacman --color auto --sync -<name>` i.e. `<leading dash><name>`
- which is erraneous, hence returning the manual

### Proposed solution
- Instead, a descriptive message should be shown. 
- this checking is possible, as pacboy also recognises `pacboy --help` and returns `did you mean 'pacboy help'?`

Something like:
```console
The variable `MINGW_PACKAGE_PREFIX` is not set.

Suggestions:
    - Launch shell in a different environment (i.e. use a different launcher)
    - Specify the command for a particular package prefix

See `pacboy help` for usage instructions.
```

### Console logs

```console
$ pacboy sync debug helix:p
:: Executing pacman --color auto --sync -helix...
usage:  pacman {-S --sync} [options] [package(s)]
options:
  -b, --dbpath <path>  set an alternate database location

... MORE ...
```

```console
$ pacboy sync debug helix:u
:: Executing pacman --color auto --sync mingw-w64-ucrt-x86_64-helix...
resolving dependencies...
looking for conflicting packages...

... MORE ...
```

### Envrionment

- Pacboy 2016.6.24
- OS: Win 10 20H2

**Comment by lazka** [comment]
Fixed via https://github.com/msys2/pactoys/pull/5
